name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 例: v1.0.0 でトリガー

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install dependencies for Windows
        if: matrix.target == 'x86_64-pc-windows-gnu'
        run: sudo apt-get install -y gcc-mingw-w64

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Rename Binary
        run: |
          mkdir dist
          if [ "${{ matrix.target }}" == "x86_64-pc-windows-gnu" ]; then
            cp target/${{ matrix.target }}/release/excelcli.exe dist/excelcli.exe
          else
            cp target/${{ matrix.target }}/release/excelcli dist/excelcli
          fi

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
